### ISSUE TITLE
Transparent Drop Menu

### ISSUE THREAD

**Issue by BryanRamirez0625** [whendovescode-shonna/helloworld#2]
When you click on "More Photos" in the Nav Menu, the dropdown menu is transparent and I'm not exactly sure why.

**Comment by whendovescode-shonna** [comment]
Hmmm, ok. Nothing comes to mind quickly.  I will take a look and get back to you.

**Comment by whendovescode-shonna** [comment]
This was fixed after noticing that the .more-photos-content css style had a typo in the background-color rule; background had a misspelling.  The underlying (root) cause was because we weren't yet using a code editor that had color-coded syntax highlighting working so as to make typos like this more obvious.
